### ISSUE TITLE
yt-dlp

### ISSUE THREAD

**Issue by hidagans** [X-Gorn/X-URL-Uploader#27]
python3 bot.py
2023-09-14 18:04:36,305 - pyrogram.crypto.aes - INFO - Using TgCrypto
2023-09-14 18:04:36,373 - asyncio - DEBUG - Using selector: EpollSelector
2023-09-14 18:04:38,650 - requests_cache.backends - DEBUG - Initializing backend: sqlite /home/coder/.lk21-requests-cache
2023-09-14 18:04:38,650 - requests_cache.backends.base - DEBUG - Initialized SQLiteDict with serializer: SerializerPipeline(name=pickle, n_stages=2)
2023-09-14 18:04:38,650 - requests_cache.backends.sqlite - DEBUG - Opening connection to /home/coder/.lk21-requests-cache.sqlite:responses
2023-09-14 18:04:38,651 - requests_cache.backends.base - DEBUG - Initialized SQLiteDict with serializer: None
2023-09-14 18:04:38,651 - requests_cache.backends.sqlite - DEBUG - Opening connection to /home/coder/.lk21-requests-cache.sqlite:redirects
2023-09-14 18:04:38,651 - requests_cache.patcher - DEBUG - Patching requests.Session with class: _ConfiguredCachedSession
2023-09-14 18:04:38,662 - requests_cache.backends - DEBUG - Initializing backend: <SQLiteCache(name=/home/coder/.lk21-requests-cache)> /home/coder/.lk21-requests-cache
2023-09-14 18:04:46,181 - plugins.youtube_dl_echo - INFO - {
    "_": "User",
    "id": 2096475011,
    "is_self": false,
    "is_contact": false,
    "is_mutual_contact": false,
    "is_deleted": false,
    "is_bot": false,
    "is_verified": false,
    "is_restricted": false,
    "is_scam": false,
    "is_fake": false,
    "is_support": false,
    "first_name": "ᴍᴀᴊᴇꜱᴛʏ ʏᴇᴀʀɪ",
    "status": "recently",
    "username": "yeari_xxm",
    "language_code": "en",
    "dc_id": 5,
    "photo": {
        "_": "ChatPhoto",
        "small_file_id": "AQADBQADPrcxGxYo4VcAEAIAA4Or9XwABIA8bQgRUQ7HAAQeBA",
        "small_photo_unique_id": "AgADPrcxGxYo4Vc",
        "big_file_id": "AQADBQADPrcxGxYo4VcAEAMAA4Or9XwABIA8bQgRUQ7HAAQeBA",
        "big_photo_unique_id": "AgADPrcxGxYo4Vc"
    }
}
2023-09-14 18:04:46,181 - filelock - DEBUG - Attempting to acquire lock 140300429860576 on /home/coder/.cache/python-tldextract/3.8.10.final__usr__7d8fdf__tldextract-3.5.0/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2023-09-14 18:04:46,182 - filelock - DEBUG - Lock 140300429860576 acquired on /home/coder/.cache/python-tldextract/3.8.10.final__usr__7d8fdf__tldextract-3.5.0/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2023-09-14 18:04:46,183 - filelock - DEBUG - Attempting to release lock 140300429860576 on /home/coder/.cache/python-tldextract/3.8.10.final__usr__7d8fdf__tldextract-3.5.0/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2023-09-14 18:04:46,183 - filelock - DEBUG - Lock 140300429860576 released on /home/coder/.cache/python-tldextract/3.8.10.final__usr__7d8fdf__tldextract-3.5.0/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2023-09-14 18:04:46,264 - pyrogram.dispatcher - ERROR - [Errno 2] No such file or directory: 'yt-dlp'
Traceback (most recent call last):
  File "/home/coder/.local/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/coder/project/X-URL-Uploader/plugins/youtube_dl_echo.py", line 184, in echo
    process = await asyncio.create_subprocess_exec(
  File "/usr/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'yt-dlp'

**Comment by X-Gorn** [comment]
make sure you have installed yt-dlp on your machine.
